### ISSUE TITLE
 Simplistic: Sliderbreak doesn't reset

### ISSUE THREAD

**Issue by C0D3-M4513R** [l3lackShark/static#18]
If you play a map fully, and have at least 1 Sliderbreak during the run (so the SB displays), submit the score, and hit the replay button, the Sliderbreak counter doesn't reset.

**Comment by l3lackShark** [comment]
https://github.com/l3lackShark/gosumemory/issues/32

**Comment by C0D3-M4513R** [comment]
thx, will close this, in favor of the issue, that you posted.
