### ISSUE TITLE
Update Checking

### ISSUE THREAD

**Issue by NightmareDreemurr** [l3lackShark/static#23]
I have a bad routing to Github so I have to use ShadowSocksR to redirect my address into another one
but it doesn't work on this program
so would you like pls add a choice in settings.ini that allows us to disable the auto-update checking?
because this is really taking a long time

**Comment by l3lackShark** [comment]
there is an [autoupdate](https://github.com/l3lackShark/gosumemory/blob/9b828379a3f7d1d4f427690b07f7633841f72a0d/main.go#L23) flag

**Comment by NightmareDreemurr** [comment]
so would u like to change line 23 to

> shouldWeUpdate := flag.Bool("autoupdate", cast.ToBool(config.Config["autoupdate"]), "Should we auto update the application?")
